"""fix relations and urls

Revision ID: 557402e09084
Revises: ad2065de04cc
Create Date: 2026-10-02 11:06:20.659585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '557402e09084'
down_revision: Union[str, None] = 'ad2065de04cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'position_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'position_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###