"""fix relations and urls

Revision ID: ad2065de04cc
Revises: c2db1b5d13f8
Create Date: 2026-10-02 10:50:44.945757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad2065de04cc'
down_revision: Union[str, None] = 'c2db1b5d13f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('position_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'employees', 'positions', ['position_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_column('employees', 'position_id')
    # ### end Alembic commands ###